[project]
name = "league-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
]

[tool.uv.workspace]
members = [
    "mcp-client",
]
